### ISSUE TITLE
Release an APK from building tutorial

### ISSUE THREAD

**Issue by LucasBonafe** [strato-emu/strato#12]
This tutorial allows the compilation of the code present in this repository to an APK, to facilitate access, could you post the result as a Release?

https://github.com/strato-emu/strato/blob/master/BUILDING.md

**Comment by Thepowa753** [comment]
Just wait for a Git Action, i think will work the same way as skyline did

**Comment by DarthVoda** [comment]
> This tutorial allows the compilation of the code present in this repository to an APK, to facilitate access, could you post the result as a Release?
> 
> https://github.com/strato-emu/strato/blob/master/BUILDING.md

The instructions given from that link that you shared seem fairly simple. Wondering why it is you haven't compiled it yourself, just to see what happens? Or are you not prepared to attempt such an experiment?

**Comment by DarthVoda** [comment]
@LucasBonafe Thank you for your reply. I get it, I don't presume it to be a simple task, which is why I asked if you were prepared to do what you had requested yourself. I wouldn't know the first thing about building with just the info given in the link you provided and coming up with a working APK file in minutes. I thought that, since you suggested it and made it seem like following a few basic steps was all that was left to do before there is a build released, well I thought you knew something about it that I didn't. Something I could have learned, as it were. Nvm, tho.

Btw, have you tried Egg as a switch emulator, or Yuzu? Everything I've read seems like Yuzu is currently best for compatibility. Followed by Skyline and then Egg (despite Egg being oldest, the first to emulate any switch game successfully, if i recall correctly, and thus been updated regularly for longest). No one mentioned Strato, since it has yet to be released, obvi

**Comment by Thepowa753** [comment]
You can get the APK from Git Action [[here is an example]](https://github.com/strato-emu/strato/actions/runs/4985037479)

**Comment by AccordiaDusk** [comment]
> You can get the APK from Git Action [[here is an example]](https://github.com/strato-emu/strato/actions/runs/4985037479)

How can I get the APK from there? I don't see any way to download it. Or is it because I'm on the mobile app?

**Comment by fanofandroidemulation** [comment]
> > You can get the APK from Git Action [[here is an example]](https://github.com/strato-emu/strato/actions/runs/4985037479)
> 
> How can I get the APK from there? I don't see any way to download it. Or is it because I'm on the mobile app?

You have to log in to download
