### ISSUE TITLE
Support for Launching ROMs from Network Locations

### ISSUE THREAD

**Issue by JimW1at** [strato-emu/strato#30]
Since nowadays most smartphones are coming without a microsd card slot, the internal storage quickly fills up with games with big file size . 

So, i stumbled upon a feature in the PPSSPP emulator called "Remote Disc Streaming", it lets you play games which are on an another device and both devices are on the same Wifi network, the device without microsd slot can access the device with microsd slot, hence solving the problem of limited storage.

This feature, if implemented in skyline could solve the microsd slot problem.

![jULmQWmIu1](https://github.com/strato-emu/strato/assets/126959019/9db62855-2323-422d-a2cf-1249a7df6ce6)

![5LYohzwEu9](https://github.com/strato-emu/strato/assets/126959019/662b5ff7-69ca-488e-ab60-ec99c5ec57a5)

**Comment by TheASVigilante** [comment]
I think it's completely feasable, but we've got our hands full atm so you'd have to wait quite a while for something like this to be implemented.

**Comment by JimW1at** [comment]
> I think it's completely feasable, but we've got our hands full atm so you'd have to wait quite a while for something like this to be implemented.

No problem, take your time i can wait.

**Comment by lynxnb** [comment]
Android somewhat allows to transparently do this. The issue with this idea is that, while it may work fine for other emulators, switch games are usually in the GigaBytes mark with regards to file size. Since the emulator has to access all of it to map it to memory before launching the game, it would mean **very long** times to boot a game.

**Comment by detectingdragon77** [comment]
> Android somewhat allows to transparently do this. The issue with this idea is that, while it may work fine for other emulators, switch games are usually in the GigaBytes mark with regards to file size. Since the emulator has to access all of it to map it to memory before launching the game, it would mean **very long** times to boot a game.

Well I feel like if the games were on a computer that is using Ethernet and the phone is connected to 5ghz wifi it should take only a minute or two. Would be nice to have the option, but completely understand if it isn't worth it to the devs.

**Comment by DominikNovosel** [comment]
I wonder if pointing Strato to a ROM folder on an SFTP server or SMB drive would have the same effect. Most built-in file managers support connections to network storage out of the box, and if the network is fast enough, it _might_ just work. Extra emphasis on _might_ because I don't know if PPSSPP does something different on the software side to properly support this.

**Comment by lynxnb** [comment]
After thinking about this, we have no plans to implement anytime soon so I'm going to close this.
