### ISSUE TITLE
Cannot control buttons + analog stick on 2 controllers at the same time

### ISSUE THREAD

**Issue by Intelparcel** [strato-emu/strato#62]
I'm not sure if this issue persists on every game, I only tested this on "Cuphead"
So in the game both controllers cannot use one/multiple buttons at the same time. For example
If the first controller is pressing A, the second one cannot use it(like if you press it won't do anything)until the first controller stop using that button
If the first controller is moving using analog stick, for example axis X+, the second controller cannot use it until the first controller stop using that axis 
It's either doing nothing or maybe got inverted axis control

**Comment by Omarpuche7** [comment]
i play on my samsung s23 ultra with two ps5 controllers.  and to map you have to turn off one and then map the other, and it gives me a headache.  In almost all multiplayer games, one of the two controllers suddenly goes out of control precisely because they are from the same brand.  The emulator does not determine them as two different controls which makes the gameplay complicated.  I can use it but sometimes it bothers me.  I hope that in the future he will make the correction, especially for those of us who take advantage of playing multiplayer to enjoy with friends.  in mmjr2 dolphin we have a great example there i have no problems as it detects them as two different controls.

**Comment by Intelparcel** [comment]
> i play on my samsung s23 ultra with two ps5 controllers. and to map you have to turn off one and then map the other, and it gives me a headache. In almost all multiplayer games, one of the two controllers suddenly goes out of control precisely because they are from the same brand. The emulator does not determine them as two different controls which makes the gameplay complicated. I can use it but sometimes it bothers me. I hope that in the future he will make the correction, especially for those of us who take advantage of playing multiplayer to enjoy with friends. in mmjr2 dolphin we have a great example there i have no problems as it detects them as two different controls.

Oh my god I tried to map two controllers one by one like you said and it worked! Although sometimes one of two goes out of control a little bit

**Comment by Intelparcel** [comment]
Mapping one by one rarely works. I'm gonna open a new issue to describe the issue more clearly

**Comment by Intelparcel** [comment]
> i play on my samsung s23 ultra with two ps5 controllers. and to map you have to turn off one and then map the other, and it gives me a headache. In almost all multiplayer games, one of the two controllers suddenly goes out of control precisely because they are from the same brand. The emulator does not determine them as two different controls which makes the gameplay complicated. I can use it but sometimes it bothers me. I hope that in the future he will make the correction, especially for those of us who take advantage of playing multiplayer to enjoy with friends. in mmjr2 dolphin we have a great example there i have no problems as it detects them as two different controls.

Dude something is not right, i used to fix this issue by binding controllers keys one by one but now it isn't working anymore
