### ISSUE TITLE
Remove trademark symbols and disclaimers from README

### ISSUE THREAD

**Issue by PeterNjeim** [strato-emu/strato#9]
There is no need to respect a third party's trademarks as your usage falls under nominative fair use

**Comment by AbandonedCart** [comment]
![image](https://github.com/strato-emu/strato/assets/1173913/583788b5-6fcf-42d6-ab80-34cc93673c58)

**Comment by PeterNjeim** [comment]
The fact that 100% of the participants in this GitHub issue abuse GitHub's custom pronoun feature creates a sense of community I've never experienced before

**Comment by PeterNjeim** [comment]
You edited your comment so now I should respond. They're not necessary as they fall under nominative fair use. If you fear confusion of affiliation simply explicitly state you aren't affiliated, I'm surprised there isn't such a message in the README already, as those disclaimers do not necessarily imply non-affiliation. Either way, if you fear you aren't protected by nominative fair use, it's still useful to explicitly state you aren't affiliated

**Comment by AbandonedCart** [comment]
I edited the comment because the point was unclear and I wasn't entirely sure how to word it to avoid making it less clear. I am not the person you are addressing with your issue, though. I just happen to know that fair use is often thrown around incorrectly and a lot of assumption is made on how liberal you can get with it.
